### ISSUE TITLE
Crash on Insert with Exposed 0.44.0

### ISSUE THREAD

**Issue by EpicSquid** [hfhbd/kotlinx-uuid#254]
I get the following error with Exposed 0.44.0, looking at the changes in the repo itself it appears they have renamed the file from "Default.kt" to "DataTypeProvider.kt" 

0.43.0: https://github.com/JetBrains/Exposed/blob/0.43.0/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/Default.kt
0.44.0: https://github.com/JetBrains/Exposed/blob/0.44.0/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/vendors/DataTypeProvider.kt

`java.lang.NoClassDefFoundError: org/jetbrains/exposed/sql/vendors/DefaultKt
	at kotlinx.uuid.exposed.UUIDColumnType.notNullValueToDB(UUIDColumnType.kt:28)
	at org.jetbrains.exposed.sql.EntityIDColumnType.notNullValueToDB(ColumnType.kt:183)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:40)
	at org.jetbrains.exposed.sql.ColumnType.valueToDB(ColumnType.kt:85)
	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:14)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:52)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:157)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:143)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
`

**Comment by hfhbd** [comment]
I don't think I can do anything on my side except creating a new release using a newer version of Expose later this day. But until Expose will be stable, these failures caused by changed abi can happen in the future though.
